### ISSUE TITLE
BAMT - "NPM Install" throws a bunch of errors.

### ISSUE THREAD

**Issue by michaelryancaputo** [chrisbraddock/node-cgmon#3]
Trying to get this installed on a BAMT USB drive that I have running (8gb, so there should be plenty of room)

This is what i get when I try to do npm install.

```
root@bamt-miner:/home/user/Downloads/node-cgmon# npm install
npm WARN package.json node-cgmon@ No repository field.
npm WARN package.json running@0.0.1 No repository field.
npm http GET https://registry.npmjs.org/reboot/0.0.1
npm http GET https://registry.npmjs.org/jsdom/0.8.10
npm http 304 https://registry.npmjs.org/jsdom/0.8.10
npm http 200 https://registry.npmjs.org/reboot/0.0.1
npm http GET https://registry.npmjs.org/reboot/-/reboot-0.0.1.tgz
npm http 200 https://registry.npmjs.org/reboot/-/reboot-0.0.1.tgz

> reboot@0.0.1 install /home/user/Downloads/node-cgmon/node_modules/reboot
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:65:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:150:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:93:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:710:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at maybeClose (child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1049:5)
gyp ERR! System Linux 2.6.32-5-686
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Downloads/node-cgmon/node_modules/reboot
gyp ERR! node -v v0.11.12-pre
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http GET https://registry.npmjs.org/htmlparser2
npm http GET https://registry.npmjs.org/nwmatcher
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/xmlhttprequest
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/cssstyle
npm http GET https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/htmlparser2
npm http 304 https://registry.npmjs.org/xmlhttprequest
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/cssstyle
npm http 304 https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/nwmatcher
npm http 304 https://registry.npmjs.org/cssom
npm ERR! reboot@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reboot@0.0.1 install script.
npm ERR! This is most likely a problem with the reboot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls reboot
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/Downloads/node-cgmon
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/hawk

> contextify@0.1.6 install /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:65:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:150:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:93:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:710:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at maybeClose (child_process.js:982:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1132:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:104:17)
gyp ERR! stack     at Pipe.close (net.js:467:12)
gyp ERR! System Linux 2.6.32-5-686
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.11.12-pre
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http GET https://registry.npmjs.org/domhandler
npm http GET https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/domelementtype
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/domhandler
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/domelementtype
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm ERR! Error: ENOENT, lstat '/home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream/transform.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/Downloads/node-cgmon
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream/transform.js
npm ERR! fstream_path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/htmlparser2/node_modules/readable-stream/transform.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:97:15)
npm ERR! Error: ENOENT, lstat '/home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/htmlparser2/node_modules/domhandler/readme.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/Downloads/node-cgmon
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/htmlparser2/node_modules/domhandler/readme.md
npm ERR! fstream_path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/htmlparser2/node_modules/domhandler/readme.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:97:15)
npm ERR! EEXIST, mkdir '/home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/hawk'
File exists: /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/hawk
Move it away, and try again. 

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/Downloads/node-cgmon
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/hawk
npm ERR! fstream_path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/hawk/index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno -17
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:97:15)
npm ERR! EEXIST, mkdir '/home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/cssstyle/lib/properties'
File exists: /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/cssstyle/lib/properties
Move it away, and try again. 

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/Downloads/node-cgmon
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/cssstyle/lib/properties
npm ERR! fstream_path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/cssstyle/lib/properties/letterSpacing.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno -17
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:97:15)
npm ERR! Error: ENOENT, lstat '/home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/tough-cookie/generate-pubsuffix.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/Downloads/node-cgmon
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/tough-cookie/generate-pubsuffix.js
npm ERR! fstream_path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/tough-cookie/generate-pubsuffix.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:97:15)
npm ERR! Error: ENOENT, lstat '/home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/htmlparser2/node_modules/domutils/lib/manipulation.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/Downloads/node-cgmon
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/htmlparser2/node_modules/domutils/lib/manipulation.js
npm ERR! fstream_path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/htmlparser2/node_modules/domutils/lib/manipulation.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:97:15)
npm ERR! Error: ENOENT, lstat '/home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/node-uuid/benchmark/bench.gnu'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/Downloads/node-cgmon
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/node-uuid/benchmark/bench.gnu
npm ERR! fstream_path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/node-uuid/benchmark/bench.gnu
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:97:15)
npm ERR! Error: ENOENT, lstat '/home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/http-signature/lib/parser.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/Downloads/node-cgmon
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/http-signature/lib/parser.js
npm ERR! fstream_path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/http-signature/lib/parser.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:97:15)
npm ERR! Error: ENOENT, lstat '/home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/mime/types/mime.types'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-5-686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/user/Downloads/node-cgmon
npm ERR! node -v v0.11.12-pre
npm ERR! npm -v 1.4.3
npm ERR! path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/mime/types/mime.types
npm ERR! fstream_path /home/user/Downloads/node-cgmon/node_modules/jsdom/node_modules/request/node_modules/mime/types/mime.types
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:97:15)
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/Downloads/node-cgmon/npm-debug.log
npm ERR! not ok code 0
```

**Comment by chrisbraddock** [comment]
Hey I've not seen this, but I think if you can install a stable version of node that'd be a step in the right direction. http://nodejs.org/download/. I'm basing that off what I'm reading [here](https://github.com/TooTallNate/node-gyp/wiki/Error%3A-%22pre%22-versions-of-node-cannot-be-installed).

I think you have a pre-release version of node installed based upon your log output:

```
gyp ERR! node -v v0.11.12-pre
```

**Comment by michaelryancaputo** [comment]
Right on, and you responded at about the exact moment that I figured it out. I used this to install a different version of Node: 
https://github.com/visionmedia/n

**Comment by chrisbraddock** [comment]
Cool. Let me know if you have other issues.

**Comment by michaelryancaputo** [comment]
II'm now not able to get it running:

info node-cgmon jQuery available, starting monitor
info node-cgmon starting monitor
info node-cgmon spawning cgminer ./start_screen.sh []
info node-cgmon sleeping 5 seconds to allow cgminer process to start
info node-cgmon could not get cgminer PID; attempted start/restart
info node-cgmon starting monitor
info node-cgmon spawning cgminer ./start_screen.sh []
info node-cgmon sleeping 5 seconds to allow cgminer process to start
info node-cgmon could not get cgminer PID; attempted start/restart
info node-cgmon starting monitor
info node-cgmon spawning cgminer ./start_screen.sh []
info node-cgmon sleeping 5 seconds to allow cgminer process to start

I'm wondering if it's a BAMT issue? Do I need to do something to make it work with BAMT?

**Comment by chrisbraddock** [comment]
Sorry I haven't ever tried BAMT. I'm curious to know what: `ps aux |grep cgminer` shows. In other words, is the cgminer process actually running? Also what output does `screen -list` show? I'm going afk but I'm happy to help tomorrow if you're still trying.

**Comment by michaelryancaputo** [comment]
I got it running, didn't realize Cgminer had to be running before the script.
Here ya go:

root@bamt-miner:/home/user# ps aux |grep cgminer
root      3959  0.0  0.0   4584  1428 ?        Ss   17:01   0:00 /usr/bin/SCREEN -d -m -S cgminer /opt/miners/cgminer/cgminer --api-listen --config /etc/bamt/cgminer.conf
root      3960  3.2  1.7 187096 53348 pts/0    Ssl+ 17:01   0:12 /opt/miners/cgminer/cgminer --api-listen --config /etc/bamt/cgminer.conf
root      5070  0.0  0.0   3304   768 pts/3    S+   17:07   0:00 grep cgminer

root@bamt-miner:/home/user# screen -list
There is a screen on:
    3959.cgminer    (03/02/2014 05:01:48 PM)    (Attached)
1 Socket in /var/run/screen/S-root.

Just wondering if you could tell me if your script transmits the data it collects to a port on the host?

**Comment by michaelryancaputo** [comment]
Also, based on the output, it looks like the date is being accessed wrong: info node-cgmon Sat Jan 17 1970 03:09:40 GMT+0000 (UTC)|S:S|MHa:1.36|MH5s:1.35|A:25|R:2|HW:0
info node-cgmon Sat Jan 17 1970 03:09:40 GMT+0000 (UTC)|S:S|MHa:1.36|MH5s:1.35|A:25|R:2|HW:0
info node-cgmon Sat Jan 17 1970 03:09:40 GMT+0000 (UTC)|S:S|MHa:1.37|MH5s:1.35|A:25|R:2|HW:0
info node-cgmon Sat Jan 17 1970 03:09:40 GMT+0000 (UTC)|S:S|MHa:1.37|MH5s:1.35|A:25|R:2|HW:0
info node-cgmon Sat Jan 17 1970 03:09:40 GMT+0000 (UTC)|S:S|MHa:1.36|MH5s:1.36|A:25|R:2|HW:0
info node-cgmon Sat Jan 17 1970 03:09:40 GMT+0000 (UTC)|S:S|MHa:1.36|MH5s:1.36|A:26|R:2|HW:0
info node-cgmon Sat Jan 17 1970 03:09:40 GMT+0000 (UTC)|S:S|MHa:1.36|MH5s:1.36|A:26|R:2|HW:0
info node-cgmon Sat Jan 17 1970 03:09:40 GMT+0000 (UTC)|S:S|MHa:1.36|MH5s:1.36|A:27|R:2|HW:0
info node-cgmon Sat Jan 17 1970 03:09:40 GMT+0000 (UTC)|S:S|MHa:1.37|MH5s:1.36|A:27|R:2|HW:0
info node-cgmon Sat Jan 17 1970 03:09:40 GMT+0000 (UTC)|S:S|MHa:1.36|MH5s:1.36|A:27|R:2|HW:0
info node-cgmon Sat Jan 17 1970

**Comment by chrisbraddock** [comment]
Well based on your earlier email I thought that node-cgmon was starting up fine but for some reason was unable to find the cgminer process. But now that you're seeing log output, I think that maybe we just didn't wait long enough.

Regarding the date, what does `date` show from a command prompt on your BAMT system?

**Comment by michaelryancaputo** [comment]
Yes sorry, you answered and I replied before saying that I figured it out :D.

My command prompt date is correct.

If I could make a suggestion: everything here is great, and works wonders, but for BAMT users, they don't really like to have to do anything with the machines after they're set up ( most of them probably don't really know how to use the command line). It would be great if there was a way to start up the script automatically when BAMT starts. I don't really know THAT much about linux, and can't figure out where the auto start script is located on the install, otherwise, i'd do it myself. I can keep looking though.

**Comment by chrisbraddock** [comment]
Good call - I'll add some info about auto-startup to the readme. I'm not sure what flavor of linux that BAMT uses, but I have node-cgmon and cgminer auto-startup configured for Xubuntu using entries in /etc/rc.local.

I'll have to look in to the date/time issue. Not sure what's up with that.

**Comment by chrisbraddock** [comment]
> Just wondering if you could tell me if your script transmits the data it collects to a port on the host?

node-cgmon doesn't transmit any data it collects outside the emails that you configure. The node-cgmon config section that mentions host ip and port only deals with the cgminer instance itself (specifically its API). Theoretically you could run node-cgmon on one box and cgminer on another and even tell cgminer to use a non-default port for its API, hence the configuration options.

Ok now I'm really going afk. :) Any other issues I'll check out in the morning.
